### ISSUE TITLE
where is the wav file？

### ISSUE THREAD

**Issue by ucasiggcas** [marl/crepe#28]
Dear，
where is audio_file.wav，Help
Please！

**Comment by ucasiggcas** [comment]
https://github.com/StevenLOL/crepe-1[https://github.com/StevenLOL/crepe-1](url)

**Comment by ucasiggcas** [comment]
[https://github.com/StevenLOL/crepe-1](url)

**Comment by ucasiggcas** [comment]
Using CREPE from the command line
This package includes a command line utility crepe and a pre-trained version of the CREPE model for easy use. To estimate the pitch of audio_file.wav, run:
$ crepe audio_file.wav

**Comment by justinsalamon** [comment]
`audio_file.wav` is just a placeholder for the file you want to analyze (there is no actual audio_file.wav). 

For example if you want to analyze a file with the path `/path/to/your/file.wav`, then you'd run:
```
$ crepe /path/to/your/file.wav
```
