### ISSUE TITLE
How to implement a real time tracker using CREPE

### ISSUE THREAD

**Issue by wingchu** [marl/crepe#32]
How can I implement a real time tracker using the crepe, as in the README file, the crepe takes only wav file to do pitch tracking like  https://marl.github.io/crepe/ ?

**Comment by jongwook** [comment]
Hi, the command-line interface only works with WAV files.

For real-time processing, you can use [the Python interface](https://github.com/marl/crepe#using-crepe-inside-python) with small chunks of real-time audio samples.

If you are not familiar with real-time audio framework in Python, check out [PyAudio](https://people.csail.mit.edu/hubert/pyaudio/).

In case you want to run your real-time pitch tracker on browser, you may also start from [the source code of the web demo](https://github.com/marl/crepe/blob/gh-pages/crepe.js#L115-L148).
