### ISSUE TITLE
Any API in Language C++?

### ISSUE THREAD

**Issue by ucasiggcas** [marl/crepe#33]
Dear,
Is there any Api for C++,
I just want to use C++ in my project,
Could U help me,Please?
Thx

**Comment by jongwook** [comment]
Hi, there is no plan to develop a C++ API.

You may call the command-line interface in your C++ program, or venture with the [TensorFlow C++ API after exporting the Keras model](https://medium.com/@hamedmp/exporting-trained-tensorflow-models-to-c-the-right-way-cf24b609d183).

Alternatively, you may be insterested in C/C++-based pitch tracker implementations like [SWIPE](https://github.com/kylebgorman/swipe) or [pYIN](https://code.soundsoftware.ac.uk/projects/pyin).
