### ISSUE TITLE
fix requirements.txt

### ISSUE THREAD

**Issue by xNickChildx** [marl/crepe#42]
Hi,
When I try to install crepe v0.0.9 i get the following error:

`Could not find a version that satisfies the requirement tensorflow==2.0 (from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
`
I have all the latest versions of tensorflow, python and pip installed and am running on Ubuntu 18.04.02

Maybe the tensorflow==2.0 line in the requirements file should read tensorflow>=2.0.0a0 ? I installed version 7 though and everything worked just fine.

**Comment by jongwook** [comment]
By the latest Python do you mean 3.8? Otherwise there should be no problem installing using `tensorflow==2.0` as [the CI page](https://travis-ci.org/marl/crepe) suggests.

Your list is missing the [RC versions of TF2.0](https://pypi.org/project/tensorflow/#history) in addition to `2.0`, and also `1.15.0`. Can you check if you're using an outdated PyPI mirror or something?

**Comment by xNickChildx** [comment]
Hey thanks for getting back to me, you were right, I was using an older version of pip. Apparently updating pip with Ubuntu gets a little fishy since the pip command was in /usr/bin and the updated version is installed to /usr/local/bin/ 

Thanks for all your help! I used the program with my guitar last night and it all worked great!

**Comment by jongwook** [comment]
Glad to hear that!

**Comment by Megan8821** [comment]
Hey, when I am installing MIDIDDSP, it shows an error of the ```crepe.``` 
Only the version below ==0.0.5 works in my computer. However, there are two troubles. 
1) If I install the crepe version in 0.0.5, it shows ```crepe 0.0.5 has requirement keras==2.1.5, but you have keras 2.8.0rc0.``` occurs. But if I downgrade the keras, the tensorflow couldn't work. 
2) if i upgrade the crepe to 0.1.2 or whatever, I met an error of 
```  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
```
and
 ```  ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
```
I've tried to certify the certificate files, but it couldn't work either.
Any solution? Thanks
