### ISSUE TITLE
Frozen Model Conversion Failed

### ISSUE THREAD

**Issue by dwarrenku** [marl/crepe#43]
I'm trying to convert the keras models you've provided to frozen graphs so they can be used in a C# application. When I do this it throws an error when I try to load the model during conversion:

```
raise ValueError('Cannot create group in read-only mode.')
ValueError: Cannot create group in read-only mode.
```
I've found [some](https://github.com/keras-team/keras/issues/6937) discussions about how this means only the model's weights are included, not its architecture and dimensions.
Could you include a json file for the files dimensions in the models branch, or include frozen models?

**Comment by jongwook** [comment]
I haven't worked with freezing TF graphs, and I'm not familiar with it. I'd suggest using CREPE's Python API to manipulate the model in a way that you'd like to:

```
import crepe
model = crepe.core.build_and_load_model('full')
model.summary()
```

The above will give you the Keras model instance, and it will have created the TF graph that you can probably freeze and save.

**Comment by dwarrenku** [comment]
Thank you! I never thought about using the API.
I loaded the model by cloning it using tf.keras.models.clone_model and it worked:

`net_model = tf.keras.models.clone_model(crepe.core.build_and_load_model('small'))`
