### ISSUE TITLE
Classification vs regression

### ISSUE THREAD

**Issue by keunwoochoi** [marl/crepe#50]
Thanks for the great repo!
I have this typical question. Have you tried to solve it as a regression problem, e.g., predicting the pitch index directly for example? or cent or hz or whatever. I'd appreciate if you could share your research experience around it.

**Comment by justinsalamon** [comment]
Yes, we tried this in some initial experiments, classification worked better so moved forward with classification. We use the gaussian trick (cf. paper) instead of 1-hot vectors during training so that close-but-not-perfect predictions aren't penalized as harshly as further off predictions.

**Comment by keunwoochoi** [comment]
> classification worked better

I see. Does it mean that regression also worked but just not as good as the classification model? I'm curious!

**Comment by justinsalamon** [comment]
Yes

**Comment by keunwoochoi** [comment]
👍 Ok thanks!
