### ISSUE TITLE
Improperly cached cents conversion matrix

### ISSUE THREAD

**Issue by tbazin** [marl/crepe#51]
Hi,
In these lines
https://github.com/marl/crepe/blob/7f0bf0593847f38df47d2760934d585ad2f618c0/crepe/core.py#L100-L103
the attribute used to check for the cached conversion matrix, `cents_mapping`, is not the actual attribute subsequently used for caching (`mapping` is used).
This makes this IF statement always-passing and the value is recomputed and recached everytime the function gets called.

**Comment by jongwook** [comment]
Great catch! Thank you for the PR, and I'll merge this shortly

**Comment by justinsalamon** [comment]
@jongwook we should accompany all bugfixes with a point release (0.0.12 in this case)

**Comment by jongwook** [comment]
@justinsalamon well, this is not a critical bug, just one extra call to `np.linspace`. I'd prefer combining this with a next release.
