### ISSUE TITLE
WavFileWarning: Chunk (non-data) not understood, skipping it.

### ISSUE THREAD

**Issue by exirmee** [marl/crepe#54]
when trying to load file to analyse:
env DEBUGPY_LAUNCHER_PORT=44929 /usr/bin/python3 /home/hatmore/.vscode/extensions/ms-python.python-2020.3.71659/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher /home/hatmore/Desktop/pyCodes/VocalRange/test.py 
/home/hatmore/Desktop/pyCodes/VocalRange/test.py:4: WavFileWarning: Chunk (non-data) not understood, skipping it.
  sr, audio = wavfile.read('test.wav')

**Comment by jongwook** [comment]
neither test.py nor test.wav seems to belong to this project. closing.
