### ISSUE TITLE
Reproducing results from paper

### ISSUE THREAD

**Issue by xavriley** [marl/crepe#70]
I'm interested in reproducing the results from the original paper - partly for experience, partly because I want to benchmark a new pitch detection algorithm.

At the moment I'm testing on the MDB-stem-synth set and have the output from crepe running into `mir_eval.io.load_time_series`. My problem is that I'm seeing low accuracy due to the inclusion of low confidence pitches in the predictions. Could someone confirm whether there was any kind of confidence threshold used in the paper?

Also knowing the makeup of the 60/20/20 test split would be useful, if the list is still available somewhere. Thanks!

**Comment by jongwook** [comment]
Hi, thanks for your interest! In case you're using the released model weights, they are trained on a mixture of datasets (listed in README.md) in order to cover a wide range of signals that we might want to use pitch tracking.

On the other hand, the evaluation reported on the paper was from a model trained and tested on a single dataset (either RWC-synth or MDB-stem-synth). It may sound disappointing, but we thought improving the performance of out-of-distribution generalization was, while being important, out of scope of the paper.

**Comment by xavriley** [comment]
Thanks for the clarification - I understand that the released model weights are likely to vary from the paper.

> I'm seeing low accuracy due to the inclusion of low confidence pitches in the predictions. Could someone confirm whether there was any kind of confidence threshold used in the paper?

Would you be able to give me any pointers on this also? Thanks again

**Comment by xavriley** [comment]
I figured this out myself - I was using `mir_eval.melody.evaluate` previously. To reproduce the paper (with the cent accuracies) I needed `mir_eval.melody.raw_pitch_accuracy`. Sorry for the noise!

**Comment by jongwook** [comment]
Ooops sorry I got late to it but glad to know if sorted out!

**Comment by xavriley** [comment]
Sorry to reopen - I've been looking at this again and coming back to this paragraph from the paper:

> ### 3.2 Methodology
> We train the model using 5-fold cross-validation, using a 60/20/20train, validation, and test split.  For MDB-stem-synth, we use artist-conditional folds, in order to avoid training and testing on the sameartist which can result in artificially high performance due to artist oralbum effects [25].

Do you have a record of the 60/20/20 splits and artist conditional folds anywhere? Thanks!

**Comment by jongwook** [comment]
Hi, it appears that I no longer have access to the data. Artist-conditional splits can be generated following [this code](https://medleydb.readthedocs.io/en/latest/_modules/medleydb/utils.html#artist_conditional_split).

**Comment by maxrmorrison** [comment]
Hi @jongwook,

I am also currently working to reproduce the original model and would benefit greatly from having access to the CREPE checkpoint trained only on MDB-stem-synth. Would you guys consider releasing that model just for researchers wanting to compare to CREPE without having to train on those 6 datasets listed in the README? I know personally that would be a huge help. =)

Thanks,
Max

**Comment by jongwook** [comment]
Hi Max, I'm sorry; I no longer have access to the CREPE experiment results that were stored in NYU servers (they probably have wiped it). It's my bad that I didn't keep a good track of it.

**Comment by maxrmorrison** [comment]
No worries. Thanks for letting me know. I've definitely lost a checkpoint or two along the way before.

**Comment by xavriley** [comment]
I'll close this one as it's resolved now - thanks again for checking this out
