### ISSUE TITLE
update PYPI package to work with hmmlearn==0.2.8 and viterbi=True

### ISSUE THREAD

**Issue by tandav** [marl/crepe#87]
PR #86 fixes a problem with `hmmlearn==0.2.8`

Can you please update PYPI package as well?
There is an old version now [0.0.12 from Jul 20, 2021](https://pypi.org/project/crepe/) which installs hmmlearn==0.2.8 and fails with viterbi=True

pip install crepe
...
Collecting hmmlearn<0.3.0,>=0.2.0
  Downloading hmmlearn-0.2.8-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (217 kB)
...

**Comment by jongwook** [comment]
https://pypi.org/project/crepe/0.0.13/
