### ISSUE TITLE
Permute layer

### ISSUE THREAD

**Issue by martingasser** [marl/crepe#88]
Hi!

I'm currently working on reimplementing and retraining a slightly modified CREPE model for a custom application. Looking at the reference implementation, I was wondering what is the purpose of the Permute layer before flattening the output of the last Conv layer.

Shouldn't the Dense layer learn the mapping to the targets regardless of the permutation order?

**Comment by jongwook** [comment]
That's right - the permute layer is totally unnecessary. That was added while we experimented with an additional RNN layer in hopes to make the prediction smoother, but it turned out it's not very helpful so was removed. Apparently we forgot to remove the permute layer.

**Comment by martingasser** [comment]
Thanks!
