### ISSUE TITLE
Support `hmmlearn==0.3.0` for M1 Mac

### ISSUE THREAD

**Issue by gudgud96** [marl/crepe#97]
`crepe` is unable to install on M1 Mac due to an issue caused by `hmmlearn < 0.3.0`, see https://github.com/hmmlearn/hmmlearn/issues/514. The issue can be reproduced by running `pip install hmmlearn==0.2.7` on an M1 Mac.

It is fixed in https://github.com/hmmlearn/hmmlearn/pull/512, but the fix is only support since `0.3.0`.

May I ask if there are upcoming plans for `crepe` to support `hmmlearn==0.3.0`? In my opinion, it would be of great value as more and more developers are now on M1 / ARM-based Mac.

**Comment by zenonasz** [comment]
is there a workaround for this? can we use crepe with hmmlearn V0.3.0?

**Comment by jongwook** [comment]
Looks like hmmlearn is source compatible, so I removed the pin in #98 and pushed [0.0.14](https://pypi.org/project/crepe/).
